---
resources:
  - name: git-resource
    type: git
    check_every: never
    source:
      uri: https://github.com/bipin1086/docker-ci-tests.git
      branch: main
  
  - name: docker-hub
    type: docker-image
    source:
      email: ((docker-hub-email))
      username: ((docker-hub-username))
      password: ((docker-hub-password))
      repository: ((docker-hub-username))/mkdocs-ci-image

  - name: version
    type: semver
    source:
      initial_version: "0.0.1"
      driver: git
      uri: https://github.com/bipin1086/docker-ci-tests.git
      branch: version
      file: version
      username: {{git-user}}
      password: {{git-token}}

jobs:
  - name: publish
    public: true
    serial: true 
    plan:
      - get: git-resource
      - get: version
        params: {bump: minor}
      - put: docker-hub
        params:
          build: git-resource
          tag_as_latest: true
          tag_file: version/version
          tag_prefix: v
      - put: version
        params: {file: version/version}
      - task: run
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: ((docker-hub-username))/mkdocs-ci-image}
          run:
            path: mkdocs
            args: ["--version"]