---
resources:
  - name: git-resource
    type: git
    source:
      uri: https://github.com/bipin1086/docker-ci-tests.git
      branch: main
  
  - name: docker-hub
    type: docker-image
    source:
      email: ((docker-hub-email))
      username: ((docker-hub-username))
      password: ((docker-hub-password))
      repository: ((docker-hub-username))/tutorial-hello-world

jobs:
  - name: publish
    public: true
    plan:
      - get: git-resource
      - put: docker-hub
        params:
          build: git-resource
      - task: run
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: ((docker-hub-username))/tutorial-hello-world}
          run:
            path: /bin/hello-world
            args: []
          params:
            NAME: ((docker-hub-username))


